#!/usr/bin/env python3
"""
Project Initializer Script

Creates a complete data engineering project structure with:
- Numbered folder hierarchy (0-7)
- dbt project configuration
- Python virtual environment
- CLAUDE.md for agentic development

Usage:
    python initialize_project.py --target "C:\\path\\to\\project"
    python initialize_project.py --target "C:\\path\\to\\project" --name "my_project" --database "MyDB"

Author: Claude Code
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from string import Template


def _load_plugin_userconfig_env():
    """Map CLAUDE_PLUGIN_OPTION_<KEY> -> <KEY> for SQL connection env vars.

    Claude Code plugin subprocesses receive userConfig values as
    CLAUDE_PLUGIN_OPTION_<KEY> environment variables, but this script expects
    bare names (e.g. SQL_SERVER). Must run before any SQL_* env var read, so
    it lives at module level.
    """
    keys = (
        'SQL_SERVER', 'SQL_DATABASE', 'SQL_AUTH_TYPE', 'SQL_USER', 'SQL_PASSWORD',
        'SQL_ENCRYPT', 'SQL_TRUST_CERT', 'SQL_DRIVER',
        'AZURE_TENANT_ID', 'AZURE_CLIENT_ID', 'AZURE_CLIENT_SECRET',
    )
    for key in keys:
        if not os.environ.get(key):
            fallback = os.environ.get(f'CLAUDE_PLUGIN_OPTION_{key}')
            if fallback:
                os.environ[key] = fallback


_load_plugin_userconfig_env()


def sanitize_name(name: str) -> str:
    """Convert project name to valid dbt project name (lowercase, underscores)."""
    # Replace spaces and hyphens with underscores
    sanitized = re.sub(r'[\s\-]+', '_', name.lower())
    # Remove any characters that aren't alphanumeric or underscore
    sanitized = re.sub(r'[^a-z0-9_]', '', sanitized)
    # Ensure it doesn't start with a number
    if sanitized and sanitized[0].isdigit():
        sanitized = 'project_' + sanitized
    return sanitized or 'data_project'


def get_display_name(sanitized_name: str) -> str:
    """Convert sanitized name back to display format (Title Case)."""
    return ' '.join(word.capitalize() for word in sanitized_name.split('_'))


def prompt_for_value(prompt: str, default: str = None) -> str:
    """Prompt user for input with optional default."""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        while True:
            user_input = input(f"{prompt}: ").strip()
            if user_input:
                return user_input
            print("  This field is required. Please enter a value.")


def create_folder_structure(target_path: Path) -> dict:
    """Create the numbered folder structure."""
    folders = {
        "0 - Architecture Setup": "Environment and tooling setup",
        "1 - Documentation": "Project documentation and requirements",
        "1 - Documentation/data-profiles": "Data profiler JSON outputs",
        "2 - Source Files": "Raw source data and samples",
        "3 - Data Pipeline": "dbt models and transformations",
        "4 - Semantic Layer": "Power BI TMDL + PBIP projects (incl. pbip-from-dbt output)",
        "5 - Report Building": "Standalone Power BI reports and dashboards",
        "6 - Data Exports": "Query results and validation outputs",
    }

    created = {}
    for folder, description in folders.items():
        folder_path = target_path / folder
        folder_path.mkdir(parents=True, exist_ok=True)
        created[folder] = str(folder_path)
        print(f"  Created: {folder}")

    return created


def create_dbt_structure(data_pipeline_path: Path) -> None:
    """Create dbt project folder structure."""
    dbt_folders = [
        "models/staging",
        "models/intermediate",
        "models/marts",
        "tests",
        "macros",
        "seeds",
        "snapshots",
        "analyses",
    ]

    for folder in dbt_folders:
        (data_pipeline_path / folder).mkdir(parents=True, exist_ok=True)

    # Create .gitkeep files in empty model folders
    for subfolder in ["staging", "intermediate", "marts"]:
        gitkeep = data_pipeline_path / "models" / subfolder / ".gitkeep"
        gitkeep.touch()


def generate_dbt_project_yml(config: dict) -> str:
    """Generate dbt_project.yml content."""
    return f"""# dbt Project Configuration
# Generated by dbt-project-initializer skill

name: '{config["project_name"]}'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: '{config["profile_name"]}'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directory for compiled and run artifacts (gitignored)
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Configure logging
log-path: "logs"

# Configuring models
models:
  {config["project_name"]}:
    # Staging layer - source transformations
    staging:
      +materialized: view
      +schema: staging
      +tags:
        - "staging"

    # Intermediate layer - business logic
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags:
        - "intermediate"

    # Marts layer - final analytics tables
    marts:
      +materialized: table
      +schema: analytics
      +tags:
        - "marts"

# Configure seeds
seeds:
  {config["project_name"]}:
    +schema: {config["schema"]}
    +quote_columns: false

# Configure snapshots
snapshots:
  {config["project_name"]}:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Configure tests - failures not stored as tables, run tests on demand
tests:
  {config["project_name"]}:
    +store_failures: false

# Documentation
vars:
  project_name: '{config["project_name"]}'

# Dispatch configuration for package compatibility
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['dbt_utils']
"""


def generate_packages_yml() -> str:
    """Generate packages.yml content."""
    return """# dbt packages
# Run 'dbt deps' to install

packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<2.0.0"]
"""


def generate_profiles_example(config: dict) -> str:
    """Generate profiles.yml.example content (template with placeholders)."""
    return f"""# dbt Profile Configuration
# Copy this file to profiles.yml and update with your connection details
# This file should NOT be committed to version control

{config["profile_name"]}:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 17 for SQL Server"
      server: localhost
      port: 1433
      database: {config["database"]}
      schema: {config["dbt_schema"]}
      user: "{{ env_var('DBT_USER', 'your_username') }}"
      password: "{{ env_var('DBT_PASSWORD', 'your_password') }}"
      trust_cert: true

    # Alternative: Windows Authentication
    # dev:
    #   type: sqlserver
    #   driver: "ODBC Driver 17 for SQL Server"
    #   server: localhost
    #   database: {config["database"]}
    #   schema: {config["dbt_schema"]}
    #   windows_login: true
"""


def generate_profiles_yml(config: dict) -> str:
    """Generate profiles.yml based on SQL_AUTH_TYPE environment variable.

    Supports: windows, sql, entra_interactive, entra_sp.
    All values read from environment — no hardcoded credentials.
    """
    auth_type = os.environ.get('SQL_AUTH_TYPE', 'sql' if os.environ.get('SQL_USER') else 'windows')
    sql_server = os.environ.get('SQL_SERVER', 'localhost')
    sql_driver = os.environ.get('SQL_DRIVER', 'ODBC Driver 17 for SQL Server')
    encrypt = os.environ.get('SQL_ENCRYPT', 'false').lower() == 'true'
    trust_cert = os.environ.get('SQL_TRUST_CERT', 'true').lower() != 'false'

    if auth_type == 'windows':
        auth_block = f"""      trusted_connection: true
      trust_cert: {str(trust_cert).lower()}"""

    elif auth_type == 'sql':
        sql_user = os.environ.get('SQL_USER', '')
        sql_password = os.environ.get('SQL_PASSWORD', '')
        auth_block = f"""      user: "{sql_user}"
      password: "{sql_password}"
      trust_cert: {str(trust_cert).lower()}"""

    elif auth_type == 'entra_interactive':
        auth_block = """      authentication: ActiveDirectoryInteractive
      encrypt: true
      trust_cert: false"""

    elif auth_type == 'entra_sp':
        tenant_id = os.environ.get('AZURE_TENANT_ID', '')
        client_id = os.environ.get('AZURE_CLIENT_ID', '')
        client_secret = os.environ.get('AZURE_CLIENT_SECRET', '')
        auth_block = f"""      authentication: ServicePrincipal
      tenant_id: "{tenant_id}"
      client_id: "{client_id}"
      client_secret: "{client_secret}"
      encrypt: true
      trust_cert: false"""

    else:
        auth_block = """      trusted_connection: true
      trust_cert: true"""

    return f"""# dbt Profile Configuration for {config["display_name"]}
# Auto-generated — auth type: {auth_type}
# WARNING: Do NOT commit this file to version control (it's in .gitignore)

{config["profile_name"]}:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "{sql_driver}"
      server: {sql_server}
      port: 1433
      database: {config["database"]}
      schema: {config["dbt_schema"]}
      encrypt: {str(encrypt).lower()}
{auth_block}
"""


def generate_project_config_yml(config: dict) -> str:
    """Generate project-config.yml content."""
    return f"""# Project Configuration
# This file defines the expected configuration for the project.
# Agents should validate against these values before performing operations.

project:
  name: "{config["display_name"]}"
  description: "{config["description"]}"
  created: "{datetime.now().strftime('%Y-%m-%d')}"

dbt:
  # Expected dbt_project.yml configuration
  project_name: "{config["project_name"]}"
  profile_name: "{config["profile_name"]}"

  # Expected profiles.yml configuration
  database:
    target: "{config["database"]}"
    server: "localhost"
    dbt_schema: "{config["dbt_schema"]}"
    driver: "ODBC Driver 17 for SQL Server"

  # Schema naming convention
  # dbt default schema (in profiles.yml) prefixes model schemas:
  #   - staging models → {config["dbt_schema"]}_staging
  #   - intermediate models → {config["dbt_schema"]}_intermediate
  #   - marts models → {config["dbt_schema"]}_analytics

  # Profile locations (in order of precedence)
  profile_locations:
    - "3 - Data Pipeline/profiles.yml"  # Project-level (gitignored)
    - "~/.dbt/profiles.yml"              # User-level

sql_server:
  # SQL Server configuration
  default_database: "{config["database"]}"
  default_server: "localhost"
  source_schema: "{config["schema"]}"  # Schema for raw source data (sql-executor loads here)

source_data:
  # Source CSV files location
  folder: "2 - Source Files"

data_pipeline:
  # dbt project location
  folder: "3 - Data Pipeline"

data_exports:
  # Query results and validation outputs
  folder: "6 - Data Exports"
"""


def generate_setup_script(config: dict) -> str:
    """Generate setup_environment.ps1 content."""
    return f'''# Setup Environment Script for {config["display_name"]} Project
# This script sets up the Python virtual environment and installs all required dependencies

param(
    [switch]$SkipVenvCreation,
    [switch]$Force,
    [switch]$Help
)

if ($Help) {{
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host "{config["display_name"]} Environment Setup" -ForegroundColor Cyan
    Write-Host "========================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Usage:" -ForegroundColor Yellow
    Write-Host "  .\\setup_environment.ps1 [-SkipVenvCreation] [-Force] [-Help]" -ForegroundColor White
    Write-Host ""
    Write-Host "Parameters:" -ForegroundColor Yellow
    Write-Host "  -SkipVenvCreation   Skip virtual environment creation (update packages only)" -ForegroundColor White
    Write-Host "  -Force              Force recreate virtual environment without prompting" -ForegroundColor White
    Write-Host "  -Help               Display this help message" -ForegroundColor White
    Write-Host ""
    exit 0
}}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "{config["display_name"]} Environment Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Get the project root directory (parent of scripts folder)
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$VenvPath = Join-Path $ProjectRoot ".venv"

# Check Python 3.12 installation specifically
Write-Host "Checking Python 3.12 installation..." -ForegroundColor Yellow
try {{
    $Python312Version = py -3.12 --version 2>&1
    Write-Host "Found: $Python312Version" -ForegroundColor Green
}}
catch {{
    Write-Host "Python 3.12 not found." -ForegroundColor Red
    Write-Host ""
    Write-Host "Please install Python 3.12:" -ForegroundColor Yellow
    Write-Host "  Option 1: winget install Python.Python.3.12" -ForegroundColor White
    Write-Host "  Option 2: Download from https://www.python.org/downloads/" -ForegroundColor White
    Write-Host ""
    Write-Host "Available Python versions on your system:" -ForegroundColor Yellow
    py --list-paths 2>&1
    exit 1
}}

# Check if .venv already exists
if (Test-Path $VenvPath) {{
    if ($Force) {{
        Write-Host "Removing existing virtual environment..." -ForegroundColor Yellow
        Remove-Item -Path $VenvPath -Recurse -Force
    }}
    elseif (-not $SkipVenvCreation) {{
        Write-Host "Virtual environment already exists at: $VenvPath" -ForegroundColor Green
        $Continue = Read-Host "Do you want to recreate it? (y/N)"
        if ($Continue -eq 'y' -or $Continue -eq 'Y') {{
            Write-Host "Removing existing virtual environment..." -ForegroundColor Yellow
            Remove-Item -Path $VenvPath -Recurse -Force
        }}
        else {{
            $SkipVenvCreation = $true
        }}
    }}
}}

# Create virtual environment with Python 3.12
if (-not $SkipVenvCreation) {{
    Write-Host ""
    Write-Host "Creating virtual environment with Python 3.12..." -ForegroundColor Yellow
    py -3.12 -m venv $VenvPath

    if ($LASTEXITCODE -eq 0) {{
        Write-Host "Virtual environment created successfully" -ForegroundColor Green
    }}
    else {{
        Write-Host "Failed to create virtual environment" -ForegroundColor Red
        exit 1
    }}
}}

# Activate virtual environment
Write-Host ""
Write-Host "Activating virtual environment..." -ForegroundColor Yellow
$ActivateScript = Join-Path $VenvPath "Scripts\\Activate.ps1"

if (Test-Path $ActivateScript) {{
    & $ActivateScript
    Write-Host "Virtual environment activated" -ForegroundColor Green
}}
else {{
    Write-Host "Activation script not found" -ForegroundColor Red
    exit 1
}}

# Upgrade pip
Write-Host ""
Write-Host "Upgrading pip..." -ForegroundColor Yellow
& "$VenvPath\\Scripts\\python.exe" -m pip install --upgrade pip --quiet
Write-Host "pip upgraded" -ForegroundColor Green

# Install required packages
Write-Host ""
Write-Host "Installing required packages..." -ForegroundColor Yellow
Write-Host ""
Write-Host "DBT Data Pipeline Dependencies:" -ForegroundColor Yellow
Write-Host "  - dbt-core (latest)" -ForegroundColor Cyan
Write-Host "  - dbt-sqlserver (latest)" -ForegroundColor Cyan
Write-Host "  - dbt-fabric (latest)" -ForegroundColor Cyan
Write-Host "  - sqlalchemy" -ForegroundColor Cyan
Write-Host ""
Write-Host "SQL Server Reader Skill Dependencies:" -ForegroundColor Yellow
Write-Host "  - pyodbc" -ForegroundColor Cyan
Write-Host "  - pandas" -ForegroundColor Cyan
Write-Host "  - python-dotenv" -ForegroundColor Cyan
Write-Host ""

& "$VenvPath\\Scripts\\pip.exe" install dbt-core dbt-sqlserver dbt-fabric pandas sqlalchemy pyodbc python-dotenv

if ($LASTEXITCODE -eq 0) {{
    Write-Host ""
    Write-Host "All packages installed successfully" -ForegroundColor Green
}}
else {{
    Write-Host ""
    Write-Host "Package installation failed" -ForegroundColor Red
    exit 1
}}

# Display installed versions
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Installed Versions:" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
& "$VenvPath\\Scripts\\dbt.exe" --version
Write-Host ""
& "$VenvPath\\Scripts\\python.exe" --version
Write-Host ""

# Test SQL Server ODBC Driver
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Checking SQL Server ODBC Driver..." -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

$OdbcCheck = & "$VenvPath\\Scripts\\python.exe" -c "import pyodbc; print('\\n'.join(pyodbc.drivers()))" 2>&1

if ($LASTEXITCODE -eq 0) {{
    Write-Host "Available ODBC Drivers:" -ForegroundColor Green
    Write-Host $OdbcCheck -ForegroundColor White

    if ($OdbcCheck -match "ODBC Driver 17 for SQL Server") {{
        Write-Host ""
        Write-Host "ODBC Driver 17 for SQL Server found" -ForegroundColor Green
    }}
    else {{
        Write-Host ""
        Write-Host "ODBC Driver 17 for SQL Server not found" -ForegroundColor Yellow
        Write-Host "   You may experience issues with SQL Server connectivity" -ForegroundColor Yellow
        Write-Host "   Download from: https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server" -ForegroundColor White
    }}
}}
else {{
    Write-Host "Could not check ODBC drivers" -ForegroundColor Yellow
}}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Virtual environment created at: $VenvPath" -ForegroundColor Green
Write-Host "All dependencies installed successfully" -ForegroundColor Green
Write-Host ""
Write-Host "Quick Start:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. Activate virtual environment:" -ForegroundColor Yellow
Write-Host "   .\\.venv\\Scripts\\Activate.ps1" -ForegroundColor White
Write-Host ""
Write-Host "2. Test dbt connection:" -ForegroundColor Yellow
Write-Host "   cd \\"3 - Data Pipeline\\"" -ForegroundColor White
Write-Host "   dbt debug" -ForegroundColor White
Write-Host ""
Write-Host "3. Load source data:" -ForegroundColor Yellow
Write-Host "   # Place CSV files in \\"2 - Source Files/\\"" -ForegroundColor White
Write-Host "   # Use /sql-executor skill to load into database" -ForegroundColor White
Write-Host ""
Write-Host "Note: profiles.yml and dbt packages are configured automatically." -ForegroundColor Green
Write-Host ""
Write-Host "For help, see: 0 - Architecture Setup\\README.md" -ForegroundColor Cyan
Write-Host ""
'''


def generate_architecture_readme(config: dict) -> str:
    """Generate README.md for Architecture Setup folder."""
    return f"""# Architecture Setup

Environment setup and dependency management for the {config["display_name"]} project.

## Quick Start

Run the setup script from the project root:

```powershell
# First-time setup (creates .venv and installs all dependencies)
.\\0 - Architecture Setup\\setup_environment.ps1

# Force recreate virtual environment
.\\0 - Architecture Setup\\setup_environment.ps1 -Force

# Skip venv creation (just install/update packages)
.\\0 - Architecture Setup\\setup_environment.ps1 -SkipVenvCreation
```

## What Gets Installed

The setup script creates a single virtual environment at the project root (`.venv`) and installs all dependencies:

### DBT Data Pipeline Dependencies
- **dbt-core** - Core dbt functionality
- **dbt-sqlserver** - SQL Server adapter for dbt
- **dbt-fabric** - Microsoft Fabric adapter for dbt
- **sqlalchemy** - Database abstraction layer
- **pyodbc** - ODBC database connectivity

### Data Processing Dependencies
- **pandas** - Data manipulation and CSV export
- **python-dotenv** - Environment variable management

## Requirements

### Python Version
- **Python 3.12** (specifically required)
- Install via: `winget install Python.Python.3.12`
- Or download from: https://www.python.org/downloads/

### SQL Server ODBC Driver
- **ODBC Driver 17 for SQL Server** (or newer)
- Verify: `python -c "import pyodbc; print(pyodbc.drivers())"`
- Download: https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server

## Project Structure

```
{config["display_name"]}/
├── .venv/                         # Virtual environment (git-ignored)
├── 0 - Architecture Setup/
│   ├── setup_environment.ps1      # Main setup script
│   ├── project-config.yml         # Project configuration
│   └── README.md                  # This file
├── 1 - Documentation/             # Project documentation
├── 2 - Source Files/              # CSV source data
├── 3 - Data Pipeline/
│   ├── dbt_project.yml
│   ├── profiles.yml               # dbt connection config (git-ignored)
│   └── profiles.yml.example       # Template for profiles.yml
├── 4 - Semantic Layer/            # Power BI TMDL + PBIP projects
├── 5 - Report Building/           # Standalone Power BI reports
└── 6 - Data Exports/              # Query results
```

## Usage After Setup

### Activate Virtual Environment
```powershell
# From project root
.\\.venv\\Scripts\\Activate.ps1
```

### Verify Installation
```powershell
# Check dbt version
dbt --version

# Check Python version
python --version

# Check installed packages
pip list
```

### Configure dbt
```powershell
cd "3 - Data Pipeline"
cp profiles.yml.example profiles.yml
# Edit profiles.yml with your connection details
dbt debug
dbt deps
```

## Database Connection

- **Server**: localhost
- **Database**: {config["database"]}
- **Schema**: {config["schema"]}
- **Driver**: ODBC Driver 17 for SQL Server

## Next Steps After Setup

1. Virtual environment created at `.venv/`
2. All dependencies installed
3. Configure `3 - Data Pipeline/profiles.yml` for dbt connection
4. Test dbt: change into `3 - Data Pipeline/` and run `dbt debug` as separate atomic commands
5. Install dbt packages: `dbt deps`
6. Place source CSV files in `2 - Source Files/`
7. Start building with personal agents!

## Support

For issues or questions:
- Review troubleshooting section in setup script
- Consult dbt documentation: https://docs.getdbt.com/
- Review Microsoft SQL Server documentation
"""


def default_settings_local() -> dict:
    """Return the default .claude/settings.local.json structure as a dict.

    Focused on what's actually needed during data pipeline builds:
    - All SQL Server MCP read-only tools (metadata discovery is constant)
    - SQL query execution (needed by agents, profiler, and reader skills)
    - Skills auto-allowed
    - dbt commands via venv path (wildcard covers run/test/compile/build/debug/deps)

    Bash file operations (cat, ls, grep, etc.) are NOT included because
    Claude Code has dedicated Read/Glob/Grep tools that are always allowed.
    """
    return {
        "permissions": {
            "allow": [
                # Skills - auto-allow all skill executions
                "Skill",

                # MCP SQL Server - connection management
                "mcp__sql-server-mcp__connect",
                "mcp__sql-server-mcp__disconnect",

                # MCP SQL Server - all read-only metadata tools
                "mcp__sql-server-mcp__get_databases",
                "mcp__sql-server-mcp__get_current_database",
                "mcp__sql-server-mcp__use_database",
                "mcp__sql-server-mcp__get_tables",
                "mcp__sql-server-mcp__get_table_schema",
                "mcp__sql-server-mcp__get_views",
                "mcp__sql-server-mcp__get_view_definition",
                "mcp__sql-server-mcp__create_view",

                # MCP SQL Server - query execution (SELECT only by tool design)
                "mcp__sql-server-mcp__execute_query",

                # dbt commands via venv (covers run, test, compile, build, debug, deps, etc.)
                "Bash(.venv/Scripts/dbt.exe:*)",

                # Git read-only operations (used constantly by agents)
                "Bash(git status:*)",
                "Bash(git log:*)",
                "Bash(git diff:*)",
                "Bash(git branch:*)",
                "Bash(git show:*)",

                # Python execution (needed for skill scripts: profiler, executor, reader)
                "Bash(python:*)",
                "Bash(py:*)",
                "Bash(.venv/Scripts/python.exe:*)",

                # Temp file cleanup (narrow patterns, safe)
                "Bash(rm tmpclaude-*)",
                "Bash(rm nul)",
            ]
        }
    }


def merge_settings_local(settings_path: Path) -> dict:
    """Merge default permissions into any pre-existing settings.local.json.

    The sql-connection skill's `configure.py` writes connection details to
    `pluginConfigs.dbt-pipeline-toolkit.options` BEFORE the project initializer
    runs (pre-stage of the orchestrator). The initializer previously overwrote
    the file unconditionally, wiping those connection options and causing
    downstream scripts to fall back to `localhost` defaults and fail.

    Contract:
    - Preserve ALL pre-existing top-level keys (especially `pluginConfigs`).
    - For `permissions.allow` / `permissions.deny`: take the union with the
      defaults, preserving insertion order and dropping duplicates.
    - If the file is present but malformed JSON, back it up alongside and
      start fresh so we don't silently corrupt user data.
    """
    defaults = default_settings_local()

    if not settings_path.exists():
        return defaults

    try:
        existing = json.loads(settings_path.read_text(encoding='utf-8'))
    except (json.JSONDecodeError, OSError) as e:
        # Don't lose the old file — preserve as .bak and start fresh
        backup = settings_path.with_suffix(settings_path.suffix + '.bak')
        try:
            settings_path.rename(backup)
            print(f"  Warning: existing settings.local.json was malformed ({e}); "
                  f"backed up to {backup.name} and generating a fresh one")
        except OSError:
            print(f"  Warning: existing settings.local.json was malformed ({e}); "
                  f"could not back up; generating fresh overwrites the old file")
        return defaults

    if not isinstance(existing, dict):
        # Malformed but parseable (e.g., a JSON array) — same policy as above
        backup = settings_path.with_suffix(settings_path.suffix + '.bak')
        try:
            settings_path.rename(backup)
            print(f"  Warning: existing settings.local.json was not a JSON object; "
                  f"backed up to {backup.name}")
        except OSError:
            pass
        return defaults

    merged = dict(existing)  # shallow copy of top-level keys

    # Deep-merge ONLY the permissions block; every other top-level key (including
    # pluginConfigs, env, model, etc.) is preserved as-is from the existing file.
    merged_permissions = dict(existing.get('permissions') or {})
    for key in ('allow', 'deny'):
        default_list = defaults['permissions'].get(key, [])
        existing_list = merged_permissions.get(key) or []
        if not isinstance(existing_list, list):
            existing_list = []
        # Preserve insertion order, dedupe: existing first, then new defaults
        seen: set[str] = set()
        union: list[str] = []
        for item in list(existing_list) + list(default_list):
            if isinstance(item, str) and item not in seen:
                seen.add(item)
                union.append(item)
        if union:
            merged_permissions[key] = union
    merged['permissions'] = merged_permissions

    return merged


def generate_gitignore() -> str:
    """Generate .gitignore content.

    Patterns MUST block: installed tools (venv, pip packages, dbt packages),
    build artifacts (target/, logs/), and credential files (profiles.yml,
    .env). Orchestrator Stage 5 runs `git add -A` immediately after the
    skill + setup script complete; anything not listed here gets committed.
    """
    return """# Python virtual environments (installed tools — NEVER commit)
.venv/
venv/
env/
ENV/
__pycache__/
*.py[cod]
*$py.class
.Python
*.egg-info/
.eggs/
*.egg

# Python test / type-check caches
.pytest_cache/
.mypy_cache/
.ruff_cache/
.coverage
htmlcov/

# dbt installed packages + build output (NEVER commit)
target/
dbt_packages/
dbt_modules/
logs/
# Explicit nested paths (belt-and-suspenders; root patterns above already
# match at any depth but listing them makes intent obvious to reviewers)
3 - Data Pipeline/target/
3 - Data Pipeline/dbt_packages/
3 - Data Pipeline/logs/

# Credentials and secrets (NEVER commit)
3 - Data Pipeline/profiles.yml
.env
.env.*
!.env.example
*.pem
*.key
secrets.yml

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
desktop.ini

# Project specific
6 - Data Exports/*.csv
6 - Data Exports/*.json

# Claude Code temporary files
tmpclaude-*-cwd
nul

# Claude Code local settings (personal preferences)
.claude/settings.local.json

# Power BI local cache
**/.pbi/cache.abf
"""


def generate_claude_md(config: dict, template_path: Path = None) -> str:
    """Generate CLAUDE.md content from template file.

    Args:
        config: Dictionary with project configuration values
        template_path: Optional path to template file. If not provided,
                      looks for template in standard location.

    Returns:
        CLAUDE.md content with placeholders replaced
    """
    # Determine template path
    if template_path is None:
        # Template must be in skill's templates folder
        script_dir = Path(__file__).parent
        template_path = script_dir.parent / "templates" / "data-project-CLAUDE.md"

    # Require template file to exist - no fallback
    if not template_path.exists():
        print()
        print("ERROR: Template file not found!")
        print(f"  Expected: {template_path}")
        print()
        print("The template file is required to generate CLAUDE.md.")
        print("Ensure the skill folder contains: templates/data-project-CLAUDE.md")
        print()
        raise FileNotFoundError(f"Required template not found: {template_path}")

    # Read template and replace placeholders
    template_content = template_path.read_text(encoding='utf-8')

    replacements = {
        "{{PROJECT_DISPLAY_NAME}}": config["display_name"],
        "{{CREATED_DATE}}": datetime.now().strftime('%Y-%m-%d'),
        "{{PROJECT_DESCRIPTION}}": config["description"],
        "{{DEFAULT_SCHEMA}}": config["schema"],
        "{{DATABASE_NAME}}": config["database"],
    }

    result = template_content
    for placeholder, value in replacements.items():
        result = result.replace(placeholder, value)

    return result


def run_setup_script(target_path: Path, skip_venv: bool = False) -> bool:
    """Run the setup environment script."""
    setup_script = target_path / "0 - Architecture Setup" / "setup_environment.ps1"

    if not setup_script.exists():
        print(f"  Warning: Setup script not found at {setup_script}")
        return False

    if skip_venv:
        print("  Skipping virtual environment setup (--skip-venv flag)")
        return True

    print("\n  Running environment setup...")
    try:
        result = subprocess.run(
            ["powershell", "-ExecutionPolicy", "Bypass", "-File", str(setup_script)],
            cwd=str(target_path),
            capture_output=True,
            text=True,
            timeout=600  # 10 minute timeout
        )

        if result.returncode == 0:
            print("  Environment setup completed successfully")
            return True
        else:
            print(f"  Warning: Setup script returned non-zero exit code: {result.returncode}")
            if result.stderr:
                print(f"  Stderr: {result.stderr[:500]}")
            return False

    except subprocess.TimeoutExpired:
        print("  Warning: Setup script timed out")
        return False
    except Exception as e:
        print(f"  Warning: Could not run setup script: {e}")
        return False


def run_dbt_deps(target_path: Path) -> bool:
    """Run dbt deps to install packages after project creation.

    This ensures that dbt packages (like dbt_utils) are installed and ready
    for use by downstream agents, without requiring manual intervention.
    """
    data_pipeline_path = target_path / "3 - Data Pipeline"
    venv_dbt = target_path / ".venv" / "Scripts" / "dbt.exe"

    # Check if dbt is available in the virtual environment
    if not venv_dbt.exists():
        print("  Warning: dbt not found in virtual environment, skipping dbt deps")
        return False

    print("\n  Installing dbt packages (dbt deps)...")
    try:
        result = subprocess.run(
            [str(venv_dbt), "deps"],
            cwd=str(data_pipeline_path),
            capture_output=True,
            text=True,
            timeout=120  # 2 minute timeout
        )

        if result.returncode == 0:
            print("  dbt packages installed successfully")
            return True
        else:
            print(f"  Warning: dbt deps returned non-zero exit code: {result.returncode}")
            if result.stderr:
                print(f"  Stderr: {result.stderr[:500]}")
            return False

    except subprocess.TimeoutExpired:
        print("  Warning: dbt deps timed out")
        return False
    except Exception as e:
        print(f"  Warning: Could not run dbt deps: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Initialize a new data engineering project"
    )
    parser.add_argument(
        "--target", "-t",
        type=str,
        required=True,
        help="Target directory for the new project"
    )
    parser.add_argument(
        "--name", "-n",
        type=str,
        help="Project name (will be sanitized for dbt)"
    )
    parser.add_argument(
        "--database", "-d",
        type=str,
        required=True,
        help="SQL Server database name (e.g., SalesDB, AnalyticsDB)"
    )
    parser.add_argument(
        "--schema", "-s",
        type=str,
        default="raw",
        help="Schema for source data/seeds loaded via sql-executor (default: raw)"
    )
    parser.add_argument(
        "--dbt-schema",
        type=str,
        default="dbo",
        help="dbt default schema prefix - creates dbo_staging, dbo_intermediate, dbo_analytics (default: dbo)"
    )
    parser.add_argument(
        "--description",
        type=str,
        help="Project description"
    )
    parser.add_argument(
        "--skip-venv",
        action="store_true",
        help="Skip virtual environment creation"
    )
    parser.add_argument(
        "--skip-deps",
        action="store_true",
        help="Skip dependency installation"
    )
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Force initialization even if target directory is not empty"
    )

    args = parser.parse_args()

    # Resolve target path
    target_path = Path(args.target).resolve()

    print("=" * 60)
    print("Project Initializer")
    print("=" * 60)
    print()

    # Interactive prompts if values not provided
    if not args.name:
        args.name = prompt_for_value("Project name (e.g., 'Sales Analytics')")

    if not args.description:
        args.description = prompt_for_value(
            "Project description",
            default=f"Data engineering project for {args.name}"
        )

    # Sanitize project name
    project_name = sanitize_name(args.name)
    display_name = get_display_name(project_name)
    profile_name = f"{project_name}_profile"

    config = {
        "project_name": project_name,
        "display_name": display_name,
        "profile_name": profile_name,
        "database": args.database,
        "schema": args.schema,
        "dbt_schema": args.dbt_schema,
        "description": args.description,
    }

    print()
    print("Configuration:")
    print(f"  Target: {target_path}")
    print(f"  Project Name: {display_name} ({project_name})")
    print(f"  Database: {config['database']}")
    print(f"  Source Schema: {config['schema']} (for raw data/seeds)")
    print(f"  dbt Schema: {config['dbt_schema']} (creates {config['dbt_schema']}_staging, {config['dbt_schema']}_intermediate, {config['dbt_schema']}_analytics)")
    print(f"  Description: {config['description']}")
    print()

    # Check if target exists
    if target_path.exists() and any(target_path.iterdir()):
        if args.force:
            print(f"Warning: Target directory is not empty: {target_path}")
            print("  Continuing anyway (--force flag specified)")
        else:
            print(f"Warning: Target directory is not empty: {target_path}")
            response = input("Continue anyway? (y/N): ").strip().lower()
            if response != 'y':
                print("Aborted.")
                return 1

    # Create target directory
    target_path.mkdir(parents=True, exist_ok=True)

    # Step 1: Create folder structure
    print("Creating folder structure...")
    create_folder_structure(target_path)

    # Step 2: Create dbt structure
    print("\nCreating dbt project structure...")
    data_pipeline_path = target_path / "3 - Data Pipeline"
    create_dbt_structure(data_pipeline_path)

    # Step 3: Generate configuration files
    print("\nGenerating configuration files...")

    # .gitignore FIRST — must exist before any subprocess that creates
    # `.venv/`, `dbt_packages/`, `target/`, `logs/`. If a later step crashes
    # after artifacts are generated but before `.gitignore` is written, the
    # orchestrator's `git add -A` would commit the venv/packages. Writing
    # this first makes that class of failure impossible.
    (target_path / ".gitignore").write_text(generate_gitignore(), encoding='utf-8')
    print("  Created: .gitignore (written first to protect against venv/package leaks)")

    # dbt_project.yml
    (data_pipeline_path / "dbt_project.yml").write_text(generate_dbt_project_yml(config), encoding='utf-8')
    print("  Created: 3 - Data Pipeline/dbt_project.yml")

    # packages.yml
    (data_pipeline_path / "packages.yml").write_text(generate_packages_yml(), encoding='utf-8')
    print("  Created: 3 - Data Pipeline/packages.yml")

    # profiles.yml.example (template with placeholders)
    (data_pipeline_path / "profiles.yml.example").write_text(generate_profiles_example(config), encoding='utf-8')
    print("  Created: 3 - Data Pipeline/profiles.yml.example")

    # profiles.yml (actual config with default local dev credentials)
    (data_pipeline_path / "profiles.yml").write_text(generate_profiles_yml(config), encoding='utf-8')
    print("  Created: 3 - Data Pipeline/profiles.yml (ready to use)")

    # project-config.yml
    arch_setup_path = target_path / "0 - Architecture Setup"
    (arch_setup_path / "project-config.yml").write_text(generate_project_config_yml(config), encoding='utf-8')
    print("  Created: 0 - Architecture Setup/project-config.yml")

    # setup_environment.ps1
    (arch_setup_path / "setup_environment.ps1").write_text(generate_setup_script(config), encoding='utf-8')
    print("  Created: 0 - Architecture Setup/setup_environment.ps1")

    # README.md for Architecture Setup
    (arch_setup_path / "README.md").write_text(generate_architecture_readme(config), encoding='utf-8')
    print("  Created: 0 - Architecture Setup/README.md")

    # CLAUDE.md
    (target_path / "CLAUDE.md").write_text(generate_claude_md(config), encoding='utf-8')
    print("  Created: CLAUDE.md")

    # .claude/settings.local.json — MERGE with any pre-existing file. The
    # sql-connection skill (`configure.py`) may have written connection config
    # here before this script ran; overwriting would wipe it out and downstream
    # scripts would fall back to localhost defaults and fail.
    claude_dir = target_path / ".claude"
    claude_dir.mkdir(parents=True, exist_ok=True)
    settings_path = claude_dir / "settings.local.json"
    merged_settings = merge_settings_local(settings_path)
    settings_path.write_text(
        json.dumps(merged_settings, indent=2), encoding='utf-8'
    )
    preserved = bool(
        isinstance(merged_settings.get('pluginConfigs'), dict)
        and merged_settings['pluginConfigs']
    )
    if preserved:
        print("  Updated: .claude/settings.local.json "
              "(merged default permissions, preserved existing pluginConfigs)")
    else:
        print("  Created: .claude/settings.local.json "
              "(default permissions — no pre-existing pluginConfigs to preserve)")

    # Step 4: Run setup script (optional)
    if not args.skip_venv and not args.skip_deps:
        print("\nSetting up Python environment...")
        setup_success = run_setup_script(target_path, args.skip_venv)

        # Step 5: Run dbt deps to install packages
        if setup_success:
            run_dbt_deps(target_path)
    else:
        print("\nSkipping environment setup (use setup_environment.ps1 manually)")

    # Summary
    print()
    print("=" * 60)
    print("Project Initialization Complete!")
    print("=" * 60)
    print()
    print(f"Project created at: {target_path}")
    print()
    print("Next steps:")
    print("  1. cd to your project directory")
    print("  2. Activate virtual environment: .\\.venv\\Scripts\\Activate.ps1")
    print("  3. Test dbt connection: change into '3 - Data Pipeline/' and run 'dbt debug'")
    print("  4. Place source CSV files in '2 - Source Files/'")
    print("  5. Start building with personal agents!")
    print()
    print("Note: dbt packages (dbt_utils) have been installed automatically.")
    print()
    auth_type = os.environ.get('SQL_AUTH_TYPE', 'sql' if os.environ.get('SQL_USER') else 'windows')
    print(f"Note: profiles.yml created with auth type: {auth_type}")
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
